export const UPDATE_COMBATANT = "UPDATE_COMBATANT";
export const NEW_COMBATANT = "NEW_COMBATANT";
export const DELETE_COMBATANT = "DELETE_COMBATANT";
export const PROGRESS_INITIATIVE = 'PROGRESS_INITIATIVE';
